// Placeholder: App string constants scaffold.
// All user-facing strings for the Aqarya app.
// Centralised here to make future localisation straightforward.

export const Strings = {
  // ─── App ───────────────────────────────────────────────────────────────────
  app: {
    name: 'Aqarya',
    tagline: 'Smart Property Intelligence',
    loading: 'Loading…',
  },

  // ─── Auth ──────────────────────────────────────────────────────────────────
  auth: {
    login: {
      title: 'Login',
      subtitle: 'Hi, welcome back',
      usernameLabel: 'Username',
      usernamePlaceholder: 'Enter your username',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter your password',
      submitButton: 'Log in',
      signingIn: 'Signing in…',
      or: 'or',
      sanadButton: 'Log in with SANAD',
      signUpPrompt: "Don't have an account? ",
      signUpLink: 'Sign up for free',
      usernameRequired: 'Username is required.',
      passwordRequired: 'Password is required.',
      signUpAlertTitle: 'Create Account',
      signUpAlertMsg: 'New accounts are provisioned through the SANAD portal. Please contact your administrator.',
      signUpAlertOk: 'OK',
      sanadAlertTitle: 'SANAD Login',
      sanadAlertMsg: 'SANAD single sign-on requires a registered SANAD digital identity. Contact your administrator to link your account.',
      sanadAlertOk: 'OK',
      orientationLine: 'Trusted property services — buy, rent, sell, and invest with DLS-verified records.',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      forgotPasswordAlertTitle: 'Account Recovery',
      forgotPasswordAlertMsg: 'Password recovery is handled through the SANAD portal or your DLS administrator. Visit the SANAD portal or contact support to regain access.',
      forgotPasswordAlertOk: 'OK',
      sanadTagline: 'Government-linked secure sign-in',
    },
    intro: {
      headline: "Jordan's Trusted Property Platform",
      subheadline: 'Verified records. Secure identity. Transparent transactions.',
      pillar1Title: 'SANAD-Verified Identity',
      pillar1Body: 'Government sign-in links your verified digital identity to every transaction.',
      pillar2Title: 'DLS Property Records',
      pillar2Body: 'Every listing is verified against official land registry data.',
      pillar3Title: 'Buy, Rent, Sell & Invest',
      pillar3Body: 'Full property lifecycle with audited, transparent records.',
      getStarted: 'Get started',
      skip: 'Skip',
    },
    accessDenied: {
      title: 'Access Denied',
      message: "You don't have permission to view this page.",
      backButton: 'Go Back',
      signOutButton: 'Sign Out',
      adminNote: 'Contact your administrator if you think this is a mistake.',
    },
    errors: {
      invalidCredentials:
        'Invalid SANAD email or password. Please try again.',
      networkError: 'Network error. Please check your connection.',
      sessionExpired: 'Your session has expired. Please sign in again.',
      generic: 'Something went wrong. Please try again.',
    },
  },

  // ─── Navigation ────────────────────────────────────────────────────────────
  nav: {
    home: 'Home',
    map: 'Map',
    portfolio: 'Portfolio',
    activity: 'Activity',
    profile: 'Profile',
    properties: 'Properties',
    messages: 'Messages',
    analytics: 'Analytics',
    auditLogs: 'Audit Logs',
    verification: 'Verification',
    chat: 'Assistant',
  },

  // ─── Home / Marketplace ───────────────────────────────────────────────────
  home: {
    greeting: 'Find your next property',
    searchPlaceholder: 'Search by city, area, or keyword…',
    marketplaceLabel: 'Marketplace',
    categoriesLabel: 'Browse by type',
    quickActionsLabel: 'Start here',
    browseForSale: 'Browse Sale Listings',
    browseForSaleSubtitle: 'Verified direct-sale properties ready to buy',
    exploreInvestments: 'Explore Investments',
    exploreInvestmentsSubtitle: 'Fractional ownership in pilot projects',
    mapPreviewLabel: 'Property Map',
    mapPreviewSubtitle: 'Interactive map view',
    mapComingSoon: 'Interactive map coming soon',
    statActiveListings: 'Active Listings',
    statVerifiedProperties: 'Verified Properties',
    statTotalInvestors: 'Investors',
    tapToExplore: 'Tap to explore →',
    noListings: 'No listings found',
    bed: 'Bed',
    bath: 'Bath',
    // Listing section labels
    saleListings: 'Sale Listings',
    rentalListings: 'Rental Listings',
    investmentProjects: 'Investment Projects',
    // Action links
    seeAll: 'See all →',
    simulate: 'Simulate →',
    // Empty states
    emptyRent: 'Rental listings are being verified and will appear soon.',
    emptyInvest: 'No published investment opportunities available right now.',
    emptyDefault: 'Try a different search or filter.',
    // Opportunity card micro-labels
    perUnit: '/unit',
    badgeAqarya: '◆ Aqarya',
    badgePremium: '★ Premium',
    badgeVerified: '✓ Verified',
    fundedSuffix: '% funded',
    irrSuffix: '% IRR',
    cityCard: {
      title: 'Explore properties near you',
      explore: 'View on Map',
    },
  },

  // ─── Market — modes, categories, filter chips ─────────────────────────────
  market: {
    // Mode labels (Buy / Rent / Invest switcher)
    buy: 'Buy',
    rent: 'Rent',
    invest: 'Invest',
    // Property category labels
    catAll: 'All',
    catApartment: 'Apartment',
    catVilla: 'Villa',
    catCommercial: 'Commercial',
    catLand: 'Land',
    // Quick filter chip labels
    filterAll: 'All',
    filterVerified: 'Verified',
    filterNew: 'New',
    filterUnder500: 'Under 500K',
    filterOver500: '500K+',
    filterAmman: 'Amman',
    filterAqaba: 'Aqaba',
  },

  // ─── Messages ─────────────────────────────────────────────────────────────
  messages: {
    screenTitle: 'Messages',
    emptyTitle: 'No conversations yet',
    emptySubtitle: 'Messages from agents, property owners, and the Aqarya team will appear here.',
    comingSoon: 'Messaging coming soon',
    comingSoonSubtitle: 'Stay in the loop with real-time updates on your listings, purchases, and investments.',
    searchPlaceholder: 'Search messages…',
    inboxLabel: 'Inbox',
    noMessagesYet: 'No messages yet.',
    sectionMyProperties: 'My Properties',
    menuMarkAllRead: 'Mark all as read',
    menuFilterListing: 'Filter by listing',
    menuFilterInvest: 'Filter by investment',
    menuRefresh: 'Refresh',
    filterListings: 'Listings',
    filterInvestments: 'Investments',
    clearFilter: 'Clear',
    optionsLabel: 'Options',
  },

  // ─── Property List ─────────────────────────────────────────────────────────
  propertyList: {
    screenTitle: 'Properties',
    searchPlaceholder: 'Search by address, city…',
    filterButton: 'Filter',
    sortButton: 'Sort',
    emptyTitle: 'No Properties Found',
    emptyMessage: 'Try adjusting your search or filters.',
    loadingMore: 'Loading more properties…',
    dailyVisitors: 'Daily Visitors',
    buildingAge: 'Building Age',
    ageUnit: 'Y',
    verifiedBadge: 'Verified',
    pendingBadge: 'Pending',
    loadingText: 'Loading marketplace…',
    homesForSale: 'Homes For Sale',
    listingSubtitle: 'Browse verified direct-sale property listings. Investment projects are shown separately.',
    sellButton: 'Sell Property',
    investButton: 'Invest',
    searchLabel: 'Search listings',
    searchInputPlaceholder: 'Search by title or location',
    applySearch: 'Apply Search',
    askingPrice: 'Asking Price',
    valuation: 'Valuation',
    directSale: 'Direct Sale',
    listingType: 'Listing Type',
    ownerLabel: 'Owner',
    verifiedAtLabel: 'Verified',
    detailsButton: 'Details',
    buyButton: 'Buy Property',
    purchaseComplete: 'Purchase complete',
    purchaseCompleteMsg: 'The property has been added to your ownership profile.',
    purchaseFailed: 'Purchase failed',
    verifiedEmpty: 'No verified listings found',
    adjustSearch: 'Adjust the search or list one of your owned homes for sale.',
  },

  // ─── Property Detail ───────────────────────────────────────────────────────
  propertyDetail: {
    screenTitle: 'Property Detail',
    houseNumber: 'House Number',
    estimatedPrice: 'Estimate House Price',
    averageAge: 'Average Age',
    dailyVisitors: 'Daily Visitors',
    buildingAge: 'Building Age',
    zoneLabel: 'Zone',
    simulateButton: 'Simulate Investment',
    chatButton: 'Ask AI Assistant',
    shareButton: 'Share',
    saveButton: 'Save',
    photosHeader: 'Photos',
    detailsHeader: 'Details',
    locationHeader: 'Location',
    nearbyHeader: 'Nearby Properties',
    ageUnit: 'Y',
    yearsUnit: 'Years',
    viewingButton: 'Sign up for a viewing',
    loadingText: 'Loading property…',
    unavailableTitle: 'Property unavailable',
    unavailableMessage: 'Try again shortly.',
    confirmBuyTitle: 'Buy Property',
    confirmBuyCancel: 'Cancel',
    confirmBuyConfirm: 'Buy',
    purchaseComplete: 'Purchase complete',
    purchaseCompleteMsg: 'The property has been transferred to your account.',
    purchaseFailed: 'Purchase failed',
    askingPrice: 'Asking Price',
    projectPrice: 'Project Price',
    directSale: 'Direct Sale',
    sharesAvailableLabel: 'Shares Available',
    propertySummary: 'Property Summary',
    ownerLabel: 'Owner',
    marketTypeLabel: 'Market type',
    ownershipTypeLabel: 'Ownership type',
    propertyValueLabel: 'Property value',
    salePriceLabel: 'Sale price',
    pricePerShareLabel: 'Price per share',
    verificationTitle: 'Verification',
    listingStatusLabel: 'Listing status',
    propertyVerificationLabel: 'Property verification',
    identityVerificationLabel: 'Identity verification',
    verifiedAtLabel: 'Verified at',
    blockchainStatusLabel: 'Blockchain status',
    proofNumberLabel: 'Proof number',
    blockchainTitle: 'Blockchain Record',
    pendingHash: 'Pending hash',
    pendingTransaction: 'Transaction will be added after anchor',
    auditTrailTitle: 'Recent Audit Trail',
    buyButton: 'Buy Property',
    simulateInvestmentButton: 'Simulate Investment',
    listingTypeLabel: 'Listing Type',
  },

  // ─── Investment Simulation ─────────────────────────────────────────────────
  investmentSimulation: {
    screenTitle: 'Investment Simulation',
    sharesLabel: 'Number of Shares',
    sharesPlaceholder: 'Enter share amount',
    pricePerShare: 'Price per Share',
    totalInvestment: 'Total Investment',
    projectedReturn: 'Projected Return',
    riskLevel: 'Risk Level',
    riskLow: 'Low',
    riskMedium: 'Medium',
    riskHigh: 'High',
    simulateButton: 'Run Simulation',
    simulatingButton: 'Simulating…',
    resultHeader: 'Simulation Result',
    investButton: 'Invest Now',
    disclaimerText:
      'This simulation is for informational purposes only and does not constitute financial advice.',
    loadingText: 'Loading opportunities…',
    featuredLabel: 'Featured Opportunities',
    screenSubtitle: 'Review sponsor quality, target yield, funding progress, and your underwriting assumptions before you invest.',
    sponsorLabel: 'Sponsor',
    perShare: '/ share',
    minimumTicket: 'Minimum ticket',
    targetIrrLabel: 'Target IRR',
    cashYieldLabel: 'Cash yield',
    fundingLabel: 'Funding',
    availableSharesLabel: 'Available',
    underwriteButton: 'Underwrite',
    changeProjectButton: 'Change Project',
    sharesToInvestLabel: 'Shares to invest',
    holdingPeriodLabel: 'Planned hold period',
    exitScenarioLabel: 'Exit Scenario',
    conservative: 'Conservative',
    base: 'Base',
    optimistic: 'Optimistic',
    exitScenarioHelper: 'Conservative reduces rent and exit growth assumptions. Optimistic assumes stronger lease-up and pricing.',
    distributionPlanLabel: 'Distribution Plan',
    cashPayout: 'Cash Payout',
    reinvestLabel: 'Reinvest',
    distributionHelper: 'Reinvestment compounds distributions instead of paying them out as cash.',
    underwritingTitle: 'Investment Underwriting',
    equityCommitment: 'Equity commitment',
    originationFee: 'Origination fee',
    legalRegistry: 'Legal and registry',
    dayOneCashOutlay: 'Day-one cash outlay',
    grossAnnualIncome: 'Gross annual income',
    mgmtDrag: 'Asset management drag',
    netAnnualCashFlow: 'Net annual cash flow',
    projectedExitValueLabel: 'Projected exit value',
    netExitProceeds: 'Net exit proceeds',
    projectedProfitLabel: 'Projected profit',
    equityMultipleLabel: 'Equity multiple',
    ownershipLabel: 'Ownership',
    commitButton: 'Commit Simulation',
    investmentRecordedTitle: 'Investment Recorded',
    viewHistoryButton: 'View History',
    underwriteAgainButton: 'Underwrite Again',
    minimumSharesLabel: 'Min shares',
  },

  // ─── Portfolio ─────────────────────────────────────────────────────────────
  portfolio: {
    screenTitle: 'My Portfolio',
    totalValue: 'Total Portfolio Value',
    totalReturn: 'Total Return',
    activeInvestments: 'Active Investments',
    emptyTitle: 'No Investments Yet',
    emptyMessage: 'Start investing in properties to build your portfolio.',
    exploreButton: 'Explore Properties',
    sharesOwned: 'Shares Owned',
    currentValue: 'Current Value',
    returnLabel: 'Return',
    loadingText: 'Loading simulation history…',
    screenSubtitle: 'Review your recorded investment commitments, cash yield, and exit assumptions.',
    recordsLabel: 'Records',
    totalOutlayLabel: 'Total Outlay',
    expectedAnnualReturn: 'Expected annual return',
    sharesOwnedLabel: 'Shares owned',
    feesLabel: 'Fees',
    totalAmountLabel: 'Total amount',
    annualCashFlowLabel: 'Annual cash flow',
    fiveYearUpsideLabel: '5Y upside',
    equityMultipleLabel: 'Equity multiple',
    emptyText: 'Run a buy simulation from the marketplace to build history.',
  },

  // ─── Chatbot ───────────────────────────────────────────────────────────────
  chatbot: {
    screenTitle: 'Aqarya Assistant',
    assistantName: 'Emmy',
    onlineStatus: 'Online',
    offlineStatus: 'Offline',
    inputPlaceholder: 'Write a Message',
    sendButton: 'Send',
    welcomeMessage:
      "Hi, I'm Emmy 👋\nI'm a manager that's here to help",
    typingIndicator: 'Emmy is typing…',
    errorMessage: 'Sorry, I could not process your request. Please try again.',
    photosLabel: 'Here are the photos:',
    viewingCTA: "Looks good 🏠, I want to sign up for a viewing",
    voiceButton: 'Voice message',
  },

  // ─── DLS Admin — Property Verification ────────────────────────────────────
  verification: {
    screenTitle: 'Property Verification',
    pendingTab: 'Pending',
    verifiedTab: 'Verified',
    rejectedTab: 'Rejected',
    approveButton: 'Approve',
    rejectButton: 'Reject',
    viewDocumentsButton: 'View Documents',
    emptyPending: 'No pending verifications.',
    emptyVerified: 'No verified properties yet.',
    emptyRejected: 'No rejected properties.',
    confirmApproveTitle: 'Approve Property?',
    confirmApproveMessage:
      'This will mark the property as verified and make it visible to citizens.',
    confirmRejectTitle: 'Reject Property?',
    confirmRejectMessage:
      'Please provide a reason for rejection.',
    rejectReasonPlaceholder: 'Enter reason…',
    confirmButton: 'Confirm',
    cancelButton: 'Cancel',
  },

  // ─── DLS Admin — Audit Logs ────────────────────────────────────────────────
  auditLogs: {
    screenTitle: 'Audit Logs',
    searchPlaceholder: 'Search logs…',
    filterAll: 'All',
    filterApproved: 'Approved',
    filterRejected: 'Rejected',
    filterInvestment: 'Investment',
    emptyTitle: 'No Logs Found',
    emptyMessage: 'There are no audit logs matching your criteria.',
    timestampLabel: 'Timestamp',
    actionLabel: 'Action',
    userLabel: 'User',
    propertyLabel: 'Property',
  },

  // ─── DLS Admin — Analytics ────────────────────────────────────────────────
  analytics: {
    screenTitle: 'Analytics',
    totalSimulations: 'Total Simulations',
    totalProperties: 'Total Properties',
    totalInvestors: 'Total Investors',
    totalVolume: 'Investment Volume',
    avgRisk: 'Avg. Risk Score',
    propertiesByZone: 'Properties by Zone',
    investmentTrend: 'Investment Trend',
    topProperties: 'Top Properties',
    periodDay: 'Day',
    periodWeek: 'Week',
    periodMonth: 'Month',
    periodYear: 'Year',
  },

  // ─── Common / Shared ───────────────────────────────────────────────────────
  common: {
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    retry: 'Retry',
    loading: 'Loading…',
    seeAll: 'See All',
    noResults: 'No results found.',
    error: 'Something went wrong.',
    success: 'Success!',
    currency: 'JOD',
    currencySymbol: '$',
  },

  // ─── Notifications ────────────────────────────────────────────────────────
  notifications: {
    screenTitle: 'Notifications',
    emptyTitle: 'No notifications yet',
    emptyBody: "You'll be notified about listing updates, messages, and investment milestones.",
    markAllRead: 'Mark all read',
    unreadLabel: 'Unread',
  },

  // ─── Saved Searches ────────────────────────────────────────────────────────
  savedSearches: {
    sectionTitle: 'Saved Searches',
    emptyMessage: 'No saved searches. Use filters on any browse screen to save a search.',
    deleteButton: 'Delete',
    saleLabel: 'Sale',
    rentLabel: 'Rent',
    investLabel: 'Invest',
  },

  // ─── Help ─────────────────────────────────────────────────────────────────
  help: {
    screenTitle: 'Help & Support',
    buyTitle: 'Buy a Property',
    buyBody:
      'Browse verified sale listings, view ownership proofs, and complete your purchase with full blockchain-backed transparency.',
    rentTitle: 'Rent a Property',
    rentBody:
      'Find verified rental listings with SANAD identity-checked landlords and transparent rental terms.',
    investTitle: 'Invest in Projects',
    investBody:
      'Buy fractional shares in Aqarya-approved investment projects. Every opportunity is trust-scored and blockchain-anchored.',
    trustTitle: 'The Aqarya Trust System',
    trustBody:
      'Every listing and opportunity goes through DLS verification, identity checks, and optional blockchain anchoring before it appears on the platform.',
    supportTitle: 'Contact Support',
    supportBody:
      'For disputes or account issues, contact Aqarya through the platform. Your data and transactions are logged and auditable.',
    faqTitle: 'Frequently Asked Questions',
    introTitle: 'How Aqarya Works',
    introBody: 'Aqarya is a trust-first property platform powered by the SANAD national identity system and DLS property records. Every action is transparent, verified, and auditable.',
    versionText: 'Version 5.0 · Aqarya Platform',
    poweredBy: 'Powered by SANAD · DLS · Blockchain',
  },

  // ─── Profile ──────────────────────────────────────────────────────────────
  profile: {
    loadingText: 'Loading profile…',
    unavailableTitle: 'Profile unavailable',
    unavailableMessage: 'Try again shortly.',
    signOut: 'Sign Out',
    sanadVerified: 'SANAD Verified',
    statListings: 'Listings',
    statMyProperties: 'My Properties',
    menuVerification: 'Verification Status',
    menuManageAccount: 'Manage Account',
    menuWallet: 'Ejod Wallet',
    menuSavedAndSearches: 'Saved & Searches',
    menuNotifications: 'Notifications',
    menuTerms: 'Terms & Conditions',
    menuLogOut: 'Log Out',
    notifOn: 'On',
    notifOff: 'Off',
    logOutTitle: 'Log Out',
    logOutMessage: 'Are you sure you want to log out?',
    verificationStatusTitle: 'Verification Status',
    propertyVerified: 'Verified',
    propertyPending: 'Pending',
    identityVerified: 'Verified',
    manageAccountTitle: 'Manage Account',
    manageAccountComingSoon: 'Account management coming soon.',
    termsTitle: 'Terms & Conditions',
    termsMessage: 'Full terms available at aqarya.jo/terms.',
    subtitle: 'Owned properties, investment history, and account settings.',
    statOwned: 'Owned',
    statSaleHomes: 'Sale Homes',
    statProjects: 'Projects',
    statInvestments: 'Investments',
    statSaved: 'Saved',
    aggregateStatsTitle: 'Aggregate Stats',
    listedForSale: 'Listed for sale',
    soldListings: 'Sold listings',
    totalOwnedValue: 'Total owned value',
    totalInvested: 'Total invested',
    sellPropertyTitle: 'Sell Your Property',
    sellPropertySubtitle: 'Choose one of your owned sale homes below to submit or resubmit it for sale verification.',
    openSellForm: 'Open Sell Listing Form',
    eligibleProperties: 'Eligible sale properties',
    preferencesTitle: 'Preferences',
    pushNotifications: 'Push notifications',
    pushNotificationsSubtitle: 'Receive updates on listings, investments, and messages.',
    languageLabel: 'Language',
    languageArabic: 'Arabic',
    languageEnglish: 'English',
    savedSearchesTitle: 'Saved Searches',
    savedSearchesEmpty: 'No saved searches. Use filters on any browse screen to save a search.',
    supportTitle: 'Support',
    supportSubtitle: 'For account issues or disputes, contact Aqarya support through the platform.',
    helpButton: 'Help & Support',
    version: 'Version 5.0 · Aqarya Platform',
    ownedPropertiesTitle: 'Owned Properties',
    investmentsTitle: 'Investments',
    saleHome: 'Sale home',
    investmentProject: 'Investment project',
    sharesOwned: 'Shares owned',
    simulatedTotal: 'Simulated total',
    annualReturn: 'Annual return',
    fiveYearReturn: '5Y return',
    listButton: 'List This Property',
    alreadyListedButton: 'Already In Sale Flow',
    alreadyListedHint: 'This property is already pending, verified, or frozen in the sale workflow.',
    deleteSearchTitle: 'Delete search?',
    deleteSearchMessage: 'This saved search will be removed.',
    notifError: 'Could not update notification preference.',
    deleteSearchError: 'Could not delete saved search.',
    errorLabel: 'Error',
  },

  // ─── Wallet ───────────────────────────────────────────────────────────────
  wallet: {
    balLabel: 'Ejod Balance',
    balSubtitle: '1 Ejod = 1 JOD · Powered by Aqarya Blockchain',
    available: 'Available',
    locked: 'Locked',
    pending: 'Pending',
    depositBtn: 'Deposit',
    withdrawBtn: 'Withdraw',
    txHistoryTitle: 'Transaction History',
    txRecords: 'records',
    emptyText: 'No transactions yet',
    emptySub: 'Deposit Ejod to get started',
    modalDepositTitle: 'Deposit Ejod',
    modalWithdrawTitle: 'Withdraw Ejod',
    modalDepositSub: 'Send JOD via CliQ. Once confirmed, Ejod will be credited 1:1 to your wallet.',
    modalWithdrawSub: 'Ejod will be burned and JOD sent to your CliQ alias or IBAN.',
    amountLabel: 'Amount (JOD)',
    depositAliasLabel: 'Your CliQ Alias / IBAN',
    withdrawAliasLabel: 'Destination CliQ Alias / IBAN',
    depositPlaceholder: 'e.g. mywallet or JO94CBJO0010000000001234567891',
    withdrawPlaceholder: 'Recipient alias or IBAN',
    cancelBtn: 'Cancel',
    invalidAmountTitle: 'Invalid amount',
    invalidAmountMsg: 'Enter a valid amount greater than 0.',
    requiredTitle: 'Required',
    depositRequiredMsg: 'Enter your CliQ alias or IBAN.',
    withdrawRequiredMsg: 'Enter your destination CliQ alias or IBAN.',
    depositInitTitle: 'Deposit Initiated',
    withdrawInitTitle: 'Withdrawal Initiated',
    depositInitMsg: 'Send JOD via CliQ using the reference above. Your Ejod balance will update once confirmed.',
    withdrawInitMsg: 'JOD will be sent to your CliQ alias within 1 business day.',
    errorTitle: 'Error',
    requestFailed: 'Request failed.',
    couldNotLoad: 'Could not load wallet.',
  },

  // ─── Map ──────────────────────────────────────────────────────────────────
  map: {
    headerLabel: 'Property Map',
    headerTitle: 'Browse properties by location',
    mapCaptionTitle: 'Jordan Property Map',
    mapCaptionSubtitle: 'Select a city below to filter listings',
    filterByCity: 'Filter by City',
    allListings: 'All Sale Listings',
    listingsIn: 'Listings in',
    noListingsTitle: 'No listings found',
    noListingsAll: 'No verified listings available right now.',
    noListingsCity: 'No verified listings in this city yet.',
    bed: 'Bed',
    bath: 'Bath',
    perMonth: '/mo',
    marketTitle: 'Jordan Property Market',
  },

  // ─── Sell Property ────────────────────────────────────────────────────────
  sell: {
    screenTitle: 'Create Sale Listing',
    ownedSubtitle: 'Complete the final sale details for a property you already own.',
    helperText: 'Submission creates a pending listing and starts property, identity, and blockchain verification.',
    titleLabel: 'Title',
    locationLabel: 'Location',
    ownerNameLabel: 'Owner Name',
    ownershipTypeLabel: 'Ownership Type',
    ownershipProofTypeLabel: 'Ownership Proof Type',
    ownershipProofNumberLabel: 'Ownership Proof Number',
    descriptionLabel: 'Description',
    askingPriceLabel: 'Asking Price',
    valuationLabel: 'Current Valuation',
    imagesLabel: 'Property Photos',
    imagesHelper: 'Add up to 6 photos from your device.',
    addPhotoButton: 'Add Photo',
    removePhoto: 'Remove',
    photoLimitReached: 'Maximum 6 photos allowed.',
    submitButton: 'Submit for Verification',
    missingFieldsTitle: 'Missing fields',
    missingFieldsMessage: 'Complete all required sale listing fields.',
    successTitle: 'Listing submitted',
    successMessage: 'Your property is now in the sale verification pipeline and will appear publicly after approval.',
    viewMarketplace: 'View Marketplace',
    failedTitle: 'Submission failed',
    // Additional fields
    cityLabel: 'City',
    propertyTypeLabel: 'Property Type',
    bedroomsLabel: 'Bedrooms',
    bathroomsLabel: 'Bathrooms',
    areaSqmLabel: 'Area (sqm)',
    amenitiesLabel: 'Amenities',
    amenitiesHelper: 'Tap to select all that apply.',
    selectPlaceholder: 'Select…',
    // Ownership type options
    ownershipTypeFreehold: 'Freehold',
    ownershipTypeLeasehold: 'Leasehold',
    // Ownership proof type options
    ownershipProofTitleDeed: 'Title Deed',
    ownershipProofMunicipalRecord: 'Municipal Record',
    // Property type options
    propTypeApartment: 'Apartment',
    propTypeVilla: 'Villa',
    propTypeCommercial: 'Commercial',
    propTypeLand: 'Land',
    // City options
    cityAmman: 'Amman',
    cityIrbid: 'Irbid',
    cityZarqa: 'Zarqa',
    cityAqaba: 'Aqaba',
    cityAlSalt: 'Al-Salt',
  },

  // ─── Thread / Messages ────────────────────────────────────────────────────
  thread: {
    loadingText: 'Loading conversation…',
    notFound: 'Thread not found.',
    emptyMessages: 'No messages yet. Start the conversation below.',
    inputPlaceholder: 'Type a message…',
    sendButton: 'Send',
  },

  // ─── Public Listing Detail ────────────────────────────────────────────────
  publicListing: {
    loadingText: 'Loading listing…',
    unavailableTitle: 'Listing unavailable',
    unavailableMessage: 'Try again shortly.',
    purchaseTitle: 'Purchase Property',
    purchaseCancel: 'Cancel',
    purchaseConfirm: 'Confirm Purchase',
    purchaseComplete: 'Purchase complete',
    purchaseCompleteMsg: 'The property has been transferred to your account.',
    purchaseFailed: 'Purchase failed',
    rentalEnquiryTitle: 'Rental Enquiry',
    rentalEnquiryMsg: 'Rental enquiries will be available when the messaging feature launches in a future update.',
    monthlyRent: 'Monthly Rent',
    askingPrice: 'Asking Price',
    projectPrice: 'Project Price',
    buyButton: 'Buy Property',
    enquireButton: 'Enquire About Rental',
    simulateButton: 'Simulate Investment',
    forSale: 'For Sale',
    forRent: 'For Rent',
    investment: 'Investment',
    saved: '♥ Saved',
    save: '♡ Save',
    valuation: 'Valuation',
    bed: 'Bed',
    bath: 'Bath',
    aboutTitle: 'About This Property',
    ownerLabel: 'Owner',
    ownershipLabel: 'Ownership',
    cityLabel: 'City',
    amenitiesTitle: 'Amenities',
    sponsorTitle: 'Sponsor',
    sellerTitle: 'Seller',
    verifiedMember: 'Verified Member',
    shareInfoTitle: 'Share Information',
    sharesAvailable: 'Shares Available',
    pricePerShare: 'Price Per Share',
    verificationTitle: 'Verification',
    statusLabel: 'Status',
    verifiedLabel: 'Verified',
    blockchainLabel: 'Blockchain',
    saveError: 'Could not update saved status.',
  },

  // ─── Investment Opportunity Detail ────────────────────────────────────────
  opportunityDetail: {
    loadingText: 'Loading opportunity…',
    notFound: 'Opportunity not found.',
    goBack: 'Back',
    trustScoreTitle: 'Trust Score',
    trustHighest: 'Highest trust tier — fully reviewed and blockchain-anchored.',
    trustPremium: 'Premium trust — reviewed with validated financial disclosures.',
    trustStandard: 'Standard verification — entry-level trust assessment passed.',
    sponsorTitle: 'Sponsor / Developer',
    riskLabel: 'Risk',
    fundingProgressTitle: 'Funding Progress',
    raisedLabel: 'Raised',
    goalLabel: 'Goal',
    totalUnitsLabel: 'Total Units',
    availableLabel: 'Available',
    pricePerUnitLabel: 'Price / Unit',
    projectedReturnsTitle: 'Projected Returns',
    targetIrrLabel: 'Target IRR',
    cashYieldLabel: 'Cash Yield',
    holdPeriodLabel: 'Hold Period',
    appreciationLabel: 'Appreciation',
    occupancyLabel: 'Occupancy',
    distributionLabel: 'Distribution',
    yearsUnit: 'Years',
    investmentStructureTitle: 'Investment Structure',
    ownershipLabel: 'Ownership',
    distributionModelLabel: 'Distribution',
    exitStrategyLabel: 'Exit Strategy',
    minimumInvestmentLabel: 'Minimum Investment',
    mgmtFeeLabel: 'Mgmt. Fee',
    aboutTitle: 'About This Opportunity',
    verificationRecordTitle: 'Verification Record',
    recordIdLabel: 'Record ID',
    blockchainHashLabel: 'Blockchain Hash',
    chainStatusLabel: 'Chain Status',
    calculatorTitle: 'Investment Calculator',
    simulatePositionLabel: 'Simulate your position in',
    numberOfUnitsLabel: 'Number of Units',
    holdingPeriodLabel: 'Holding Period',
    exitScenarioLabel: 'Exit Scenario',
    reinvestLabel: 'Reinvest distributions (compound)',
    estimatedEntryCostLabel: 'Estimated Entry Cost',
    platformFeeNote: '+ platform fee (1.5%) + government fee (0.75%)',
    minInvestmentLabel: 'Min. Investment',
    simulateButton: 'Invest Now',
    simulationCompleteTitle: 'Investment Confirmed',
    totalEntryCostLabel: 'Total Entry Cost',
    annualCashFlowLabel: 'Annual Net Cash Flow',
    projectedExitValueLabel: 'Projected Exit Value',
    projectedProfitLabel: 'Projected Profit',
    equityMultipleLabel: 'Equity Multiple',
    modalDisclosure: 'Funds have been deducted from your Ejod Wallet. All projections are estimates based on target financial assumptions.',
    closeButton: 'Done',
    simulationFailedTitle: 'Investment failed',
    insufficientBalanceTitle: 'Insufficient Balance',
    insufficientBalanceMsg: 'You do not have enough Ejod balance for this investment. Please deposit funds first.',
    stageLabel: 'Stage',
    holdLabel: 'Hold',
    irrLabel: 'IRR',
    yieldLabel: 'Yield',
  },

  // ─── My Properties ───────────────────────────────────────────────────────
  myProperties: {
    screenTitle: 'My Properties',
    subtitle: 'Your owned properties and investment assets.',
    loadingText: 'Loading your properties…',
    errorText: 'Unable to load your properties.',
    emptyTitle: 'No Properties Yet',
    emptySubtitle: 'Properties you register or acquire will appear here.',
    addListingButton: 'New Sale Listing',
    saleType: 'Sale Home',
    investmentType: 'Investment Project',
    valueLabel: 'Value',
    priceLabel: 'Asking Price',
    sharesLabel: 'Shares',
    propVerificationLabel: 'Property',
    idVerificationLabel: 'Identity',
    listButton: 'List for Sale',
    alreadyListedButton: 'In Sale Flow',
    alreadyListedHint: 'Already pending, verified, or frozen in the sale workflow.',
    simulateButton: 'Simulate',
    favoritesTab: 'Favorites',
    searchPropertiesPlaceholder: 'Search properties…',
    searchFavoritesPlaceholder: 'Search favorites…',
    favoritesEmptyTitle: 'No Favorites Yet',
    favoritesEmptySubtitle: 'Tap ♥ on any property to save it here.',
    noSearchResults: 'No results',
    noPropertiesMatch: 'No properties match',
    noFavoritesMatch: 'No favorites match',
    removeFromFavTitle: 'Remove from Favorites',
    removeFromFavMessage: 'Remove this item from your saved list?',
    removeFromFavConfirm: 'Remove',
    removeFromFavError: 'Could not remove from favorites.',
  },

  // ─── Other Role ───────────────────────────────────────────────────────────
  otherRole: {
    title: 'Authenticated',
    roleLabel: 'Role',
    unknown: 'unknown',
    note: 'This account is signed in, but no dedicated app stack is assigned yet.',
    signOut: 'Sign Out',
  },

  // ─── Accessibility ─────────────────────────────────────────────────────────
  a11y: {
    closeModal: 'Close modal',
    goBack: 'Go back',
    searchIcon: 'Search',
    filterIcon: 'Filter',
    menuIcon: 'Open menu',
    heartIcon: 'Save property',
    shareIcon: 'Share property',
    sendMessage: 'Send message',
    playVoice: 'Play voice message',
    propertyImage: 'Property image',
    avatarImage: 'User avatar',
  },

  // ─── Admin ─────────────────────────────────────────────────────────────────
  admin: {
    // Navigation titles
    nav: {
      commandCenter: 'Command Center',
      saleListings: 'Sale Listings',
      auditLogs: 'Audit Logs',
      analytics: 'Analytics',
      propertyDetail: 'Property Detail',
      investmentReview: 'Investment Review',
      opportunityDetail: 'Opportunity Detail',
      userManagement: 'User Management',
      userProfile: 'User Profile',
      moderation: 'Moderation',
      reportDetail: 'Report Detail',
      announcements: 'Announcements',
      newAnnouncement: 'New Announcement',
      helpContent: 'Help Content',
      signOut: 'Sign Out',
    },
    // Dashboard
    dashboard: {
      live: 'LIVE',
      title: 'Command Center',
      subtitle: 'Platform overview — pending reviews, threads, and recent activity.',
      loadingSummary: 'Loading platform summary…',
      sectionPlatformOverview: 'PLATFORM OVERVIEW',
      sectionRecentActivity: 'RECENT ACTIVITY',
      sectionOperations: 'OPERATIONS',
      statPendingListings: 'Pending Listings',
      statPendingInvestments: 'Pending Investments',
      statPendingProviders: 'Pending Providers',
      statOpenThreads: 'Open Threads',
      statCitizens: 'Citizens',
      statOpenReports: 'Open Reports',
      statQualityFlags: 'Quality Flags',
      tileSaleListings: 'Sale Listings',
      tileInvestmentReview: 'Investment Review',
      tileUserManagement: 'User Management',
      tileModeration: 'Moderation',
      tileAnalytics: 'Analytics',
      tileAnnouncements: 'Announcements',
      tileAuditLogs: 'Audit Logs',
      tileHelpContent: 'Help Content',
    },
    // Property Verification
    propertyVerification: {
      title: 'Sale Listings',
      subtitle: 'Verify, freeze, anchor, and inspect submitted property listings.',
      filterAll: 'All',
      loadingText: 'Loading sale listings…',
      errorLoad: 'Unable to load sale listings.',
      listingCount: 'listing',
      listingCountPlural: 'listings',
      labelSeller: 'Seller',
      actionView: 'View',
      actionVerify: 'Verify',
      actionFreeze: 'Freeze',
      actionAnchor: 'Anchor',
      confirmVerifyTitle: 'Verify listing?',
      confirmVerifyMsg: 'This approves the listing and makes it public in for-sale surfaces.',
      confirmFreezeTitle: 'Freeze listing?',
      confirmFreezeMsg: 'This removes the listing from active citizen visibility while preserving its record.',
      confirmAnchorTitle: 'Anchor blockchain proof?',
      confirmAnchorMsg: 'This records the property verification on the configured blockchain adapter.',
      alertDone: 'Done',
      alertActionFailed: 'Action Failed',
      alertActionError: 'Unable to complete selected action.',
      emptyTitle: 'No listings here',
      emptyText: 'Change the filter or wait for more submissions.',
    },
    // Investment Review
    investmentReview: {
      title: 'Investment Review',
      subtitle: 'Review and approve submitted investment opportunities.',
      filterAll: 'All',
      loadingText: 'Loading investment opportunities…',
      errorLoad: 'Unable to load investment opportunities.',
      opportunityCount: 'opportunity',
      opportunityCountPlural: 'opportunities',
      actionView: 'View',
      actionApprove: 'Approve',
      actionPublish: 'Publish',
      confirmApproveTitle: 'Approve Opportunity?',
      confirmApproveMsg: 'Mark this opportunity as approved and ready for publishing.',
      confirmPublishTitle: 'Publish Opportunity?',
      confirmPublishMsg: 'Make this opportunity visible to all citizen investors.',
      alertDone: 'Done',
      alertActionCompleted: 'Action completed.',
      alertActionFailed: 'Action Failed',
      alertActionError: 'Unable to complete selected action.',
      emptyTitle: 'No opportunities here',
      emptyText: 'Change the filter or wait for new submissions.',
      labelIRR: 'IRR',
      labelPerShare: '/share',
      labelRisk: 'Risk',
    },
    // User Management
    userManagement: {
      title: 'User Management',
      subtitle: 'Browse all platform users and manage provider verification.',
      filterAll: 'all',
      filterTypeLabel: 'ACCOUNT TYPE',
      filterStatusLabel: 'PROVIDER STATUS',
      noProfile: 'No Profile',
      loadingText: 'Loading users…',
      errorLoad: 'Unable to load users.',
      userCount: 'user',
      userCountPlural: 'users',
      statProps: 'Props',
      statInvest: 'Invest',
      statThreads: 'Threads',
      emptyTitle: 'No users found',
      emptyText: 'Try adjusting the filters.',
      joinedPrefix: 'Joined ',
    },
    // Moderation Queue
    moderationQueue: {
      filterAll: 'All',
      filterStatusLabel: 'Status',
      filterTypeLabel: 'Type',
      loadingText: 'Loading reports…',
      errorLoad: 'Unable to load moderation reports.',
      reportCount: 'report',
      reportCountPlural: 'reports',
      targetListing: 'Listing',
      targetOpportunity: 'Opportunity',
      emptyTitle: 'No reports found',
      emptyText: 'Adjust filters or check back later.',
    },
    // Moderation Detail
    moderationDetail: {
      labelSubmitted: 'Submitted',
      badgeListing: 'Listing Report',
      badgeOpportunity: 'Opportunity Report',
      sectionReportedListing: 'Reported Listing',
      sectionReportedOpportunity: 'Reported Opportunity',
      sectionReportedEntity: 'Reported Entity',
      sectionReportDetails: 'Report Details',
      sectionQualityFlags: 'Quality Flags',
      sectionReviewHistory: 'Review History',
      labelTitle: 'Title',
      labelLocation: 'Location',
      labelStatus: 'Status',
      labelReason: 'Reason',
      labelReporter: 'Reporter',
      labelReviewedAt: 'Reviewed at',
      reporterNotes: "Reporter's Notes",
      noQualityFlags: 'No quality flags detected for this target.',
      qualityFlagsSubtitle: 'System-detected signals for this',
      entityNotFound: 'Target entity not found — may have been removed.',
      viewListing: 'View listing →',
      viewOpportunity: 'View opportunity →',
      actionMarkUnderReview: 'Mark Under Review',
      actionResolve: 'Resolve',
      actionDismiss: 'Dismiss',
      confirmMarkUnderReviewTitle: 'Mark Under Review',
      confirmMarkUnderReviewMsg: 'Mark this report as under review?',
      confirmResolveTitle: 'Resolve Report',
      confirmResolveMsg: 'Mark this report as resolved?',
      confirmDismissTitle: 'Dismiss Report',
      confirmDismissMsg: 'Dismiss this report? No action will be recorded against the target.',
      closedBannerPrefix: 'This report is',
      closedBannerSuffix: '. No further actions available.',
      errorLoad: 'Failed to load report.',
      errorAction: 'Action failed.',
    },
    // Audit Logs
    auditLogs: {
      filterAll: 'All',
      expandMetadata: 'metadata ▼',
      collapseMetadata: 'metadata ▲',
      loadingText: 'Loading audit logs…',
      errorLoad: 'Unable to load audit logs.',
      logCount: 'log',
      logCountPlural: 'logs',
      labelAction: 'Action',
      labelAdmin: 'Admin',
      labelTarget: 'Target',
      labelTargetId: 'Target ID',
      labelTimestamp: 'Timestamp',
      noLogsTitle: 'No audit logs found',
      noLogsText: 'Audit activity will appear here.',
      labelRole: 'Role',
      labelActor: 'Actor',
      labelProperty: 'Property',
      filterActionType: 'Action Type',
      applyFilters: 'Apply Filters',
      loadingMore: 'Loading more…',
    },
    // Analytics
    analytics: {
      live: 'LIVE',
      lastAnchorPrefix: 'Last anchor:',
      noAnchor: 'No anchor recorded yet',
      healthScoreLabel: 'OPERATIONAL HEALTH SCORE',
      healthStrong: 'Strong',
      healthNeedsAttention: 'Needs Attention',
      healthCritical: 'Critical',
      sectionPropertyOps: 'Property Operations',
      sectionInvestmentOps: 'Investment Operations',
      sectionProviderVerif: 'Provider Verification',
      sectionModerationSafety: 'Moderation & Safety',
      sectionSupportComms: 'Support & Communications',
      sectionInsights: 'Actionable Insights',
      collapse: '▲ Collapse',
      expand: '▼ Expand',
      cardPropertyPipeline: 'Property Pipeline',
      cardOpportunityPipeline: 'Opportunity Pipeline',
      cardProviderStatus: 'Provider Status Breakdown',
      cardReportPipeline: 'Report Pipeline',
      cardContentAnnouncements: 'Announcements & Content',
      tileTotalListings: 'Total Listings',
      tilePendingReview: 'Pending Review',
      tileAnchoredRecords: 'Anchored Records',
      tileSimulations: 'Simulations',
      tilePublished: 'Published',
      tileReviewBacklog: 'Review Backlog',
      tileVerifiedProviders: 'Verified Providers',
      tileOpenReports: 'Open Reports',
      tileQualityFlags: 'Quality Flags',
      tileSupportThreads: 'Support Threads',
      tileRecentMessages: 'Recent Messages',
      statCitizens: 'Citizens',
      statListings: 'Listings',
      statOpportunities: 'Opportunities',
      statProviders: 'Providers',
      statPending: 'Pending',
      statNeedsChanges: 'Needs Changes',
      statVerified: 'Verified',
      statRejected: 'Rejected',
      statFrozen: 'Frozen',
      statSold: 'Sold',
      statDraft: 'Draft',
      statSubmitted: 'Submitted',
      statUnderReview: 'Under Review',
      statApproved: 'Approved',
      statPublished: 'Published',
      statUnverified: 'Unverified',
      statSuspended: 'Suspended',
      statOpen: 'Open',
      statResolved: 'Resolved',
      statDismissed: 'Dismissed',
      statActiveAnnouncements: 'Active Announcements',
      statArchived: 'Archived',
      statActiveHelpBlocks: 'Active Help Blocks',
      barVerificationCoverage: 'Verification Coverage',
      barAnchoringCoverage: 'Anchoring Coverage',
      barFrozenInventory: 'Frozen Inventory',
      barPublishRate: 'Publish Rate (of reviewed)',
      barVerifiedRate: 'Verified Rate',
      barResolutionRate: 'Resolution Rate',
      subQueueClear: 'Queue clear',
      subNoVolume: 'No volume',
      subNeedsAttention: 'Needs attention',
      subNeedsAction: 'Needs action',
      subClear: 'Clear',
      subAllResolved: 'All resolved',
      subUnresolved: 'Unresolved',
      subLast7Days: 'Last 7 days',
      investSimulations: 'Investment simulations',
      errorLoad: 'Unable to load analytics.',
      errorTitle: 'Could not load analytics',
      retryButton: 'Retry',
      insightPropPendingSuffix: ' listings awaiting verification',
      insightPropPendingDetail: 'Review and process pending property submissions to keep the sale pipeline moving.',
      insightFreezeTitle: 'High frozen-property ratio',
      insightFreezeDetail: 'Prioritise investigations and remediation to reduce frozen inventory.',
      insightAnchorTitle: 'Blockchain anchoring backlog',
      insightAnchorDetail: 'Anchor additional verified records to strengthen auditability.',
      insightInvestReviewSuffix: ' investment opportunities need review',
      insightInvestReviewDetail: 'Submitted and under-review opportunities are waiting for admin action.',
      insightProviderReviewSuffix: ' provider applications pending',
      insightProviderReviewDetail: 'Review and approve or reject pending provider account applications.',
      insightModerationSuffix: ' moderation reports unresolved',
      insightModerationDetail: 'Open and under-review reports require admin action to keep the platform safe.',
      insightQualityFlagsSuffix: ' unresolved quality flags',
      insightQualityFlagsDetail: 'Inspect and resolve open quality flags on listings and investment opportunities.',
      insightStableTitle: 'Operational posture is healthy',
      insightStableDetail: 'All key metrics — verification, review pipelines, moderation — are within expected thresholds.',
    },
    // Announcements
    announcements: {
      filterAll: 'All',
      filterActive: 'Active',
      filterArchived: 'Archived',
      newButton: '+ New',
      archiveButton: 'Archive',
      announcementCount: 'announcement',
      announcementCountPlural: 'announcements',
      errorLoad: 'Failed to load announcements.',
      emptyTitle: 'No announcements found',
      emptyText: 'Create one with the "+" button or adjust the filter.',
    },
    // Create Announcement
    createAnnouncement: {
      sectionMessage: 'Message',
      sectionType: 'Type',
      sectionAudience: 'Target Audience',
      labelTitle: 'TITLE',
      labelBody: 'BODY',
      labelTargetUserId: 'TARGET USER ID',
      titlePlaceholder: 'Short, clear subject line',
      bodyPlaceholder: 'Full announcement text…',
      userIdPlaceholder: "Enter the user's UUID",
      footerNote: 'This announcement will be delivered immediately to the selected audience.',
      submitButton: 'Send Announcement',
      errorSendTitle: 'Failed to send',
      errorGeneric: 'An error occurred. Please try again.',
      typeSystem: 'System',
      typeSystemDesc: 'Platform-wide notices',
      typeInvestmentMilestone: 'Investment Milestone',
      typeInvestmentMilestoneDesc: 'Funding & ROI updates',
      typeListingStatus: 'Listing Status',
      typeListingStatusDesc: 'Property lifecycle changes',
      audienceAllCitizensDesc: 'All citizen accounts',
      audienceAllProvidersDesc: 'All provider accounts',
      audienceOneUserDesc: 'A specific user by ID',
    },
    // Content Management
    contentManagement: {
      subtitle: 'Manage the content blocks displayed on the citizen Help screen. Toggle active/inactive to control visibility without deleting content.',
      labelTitle: 'TITLE',
      labelBody: 'BODY',
      labelIcon: 'ICON',
      iconPlaceholder: '🏠',
      activeLabel: 'Active',
      activeDesc: 'Visible to citizens on Help screen',
      saveButton: 'Save',
      cancelButton: 'Cancel',
      errorSaveTitle: 'Save failed',
      errorSaveRetry: 'Please try again.',
      emptyTitle: 'No content blocks found',
      emptyText: 'Content blocks are seeded at startup. Check your database seed configuration.',
      errorLoad: 'Failed to load content blocks.',
      statusActive: 'Active',
      statusInactive: 'Inactive',
    },
    // Property Detail
    propertyDetail: {
      sectionEntity: 'Listing Profile',
      sectionDetails: 'Property Details',
      sectionFinancials: 'Financials',
      sectionVerificationHistory: 'Verification History',
      sectionAdminActions: 'Admin Actions',
      sectionBlockchain: 'Blockchain Record',
      sectionSellerLinkage: 'Seller Linkage',
      sectionVerificationBlockchain: 'Verification & Blockchain',
      sectionVerificationPayload: 'Verification Payload',
      sectionAuditEvents: 'Audit Events',
      sectionReviewActions: 'Review Actions',
      labelAsking: 'Asking',
      labelValuation: 'Valuation',
      labelShares: 'Shares',
      labelType: 'Type',
      labelCity: 'City',
      labelArea: 'Area',
      labelBedrooms: 'Bedrooms',
      labelBathrooms: 'Bathrooms',
      labelFloor: 'Floor',
      labelFurnished: 'Furnished',
      labelOwner: 'Owner',
      labelSubmitted: 'Submitted',
      labelUpdated: 'Updated',
      labelAnchorTx: 'Anchor Tx',
      labelAnchoredAt: 'Anchored At',
      anchorNotRecorded: 'Not recorded',
      labelSellerName: 'Seller name',
      labelUsername: 'Username',
      labelUserId: 'User ID',
      labelAvailableShares: 'Available shares',
      labelOwnershipType: 'Ownership type',
      labelProofType: 'Proof type',
      labelProofNumber: 'Proof number',
      labelLifecycle: 'Lifecycle',
      labelPropertyVerification: 'Property verification',
      labelIdentityVerification: 'Identity verification',
      labelVerificationRecord: 'Verification record',
      labelBlockchainStatus: 'Blockchain status',
      labelBlockchainHash: 'Blockchain hash',
      labelBlockchainTx: 'Blockchain tx',
      noAuditEvents: 'No audit events recorded for this property.',
      notAssigned: 'Not assigned',
      pendingText: 'Pending',
      notAnchoredText: 'Not anchored',
      reviewerNotesBanner: 'Reviewer Notes',
      rejectionReasonBanner: 'Rejection Reason',
      notesRejectLabel: 'Rejection reason *',
      notesRequestChangesLabel: 'Reviewer notes *',
      notesRejectPlaceholder: 'Enter the reason for rejection…',
      notesRequestChangesPlaceholder: 'Describe what changes the owner needs to make…',
      confirmActionPrompt: 'Confirm this action?',
      actionVerify: 'Verify',
      actionReject: 'Reject',
      actionRequestChanges: 'Request Changes',
      actionFreeze: 'Freeze',
      actionAnchor: 'Anchor',
      actionSendBack: 'Send Back',
      cancelButton: 'Cancel',
      confirmButton: 'Confirm',
      backToListings: 'Back to Listings',
      alertDone: 'Done',
      alertActionCompleted: 'Action completed.',
      alertActionFailed: 'Action failed',
      alertActionError: 'Unable to complete the action.',
      alertNotesRequiredTitle: 'Notes required',
      alertNotesRequiredMsg: 'Please enter notes before submitting this action.',
      loadingText: 'Loading property profile…',
      errorUnavailable: 'Property unavailable',
      errorTryAgain: 'Try again shortly.',
      errorLoad: 'Failed to load property.',
    },
    // Investment Detail
    investmentDetail: {
      sectionSponsor: 'Sponsor & Classification',
      sectionFinancials: 'Financials',
      sectionStructure: 'Structure',
      sectionAdminActions: 'Admin Actions',
      sectionReviewBlockchain: 'Review & Blockchain',
      sectionReviewActions: 'Review Actions',
      labelSponsor: 'Sponsor',
      labelRisk: 'Risk',
      labelProperty: 'Property',
      labelCity: 'City',
      labelIRR: 'Target IRR',
      labelCashYield: 'Cash Yield',
      labelPerShare: 'Per Share',
      labelMinInvestment: 'Min. Investment',
      labelHoldPeriod: 'Hold Period',
      labelTotalShares: 'Total Shares',
      labelAvailableShares: 'Available Shares',
      labelSharesSold: 'Shares Sold',
      labelSubmitted: 'Submitted',
      labelAssetClass: 'Asset class',
      labelStage: 'Stage',
      labelRiskBand: 'Risk band',
      labelTrustBadge: 'Trust badge',
      labelTrustScore: 'Trust score',
      labelPricePerShare: 'Price per share',
      labelFundingGoal: 'Funding goal',
      labelFundedAmount: 'Funded amount',
      labelMinShares: 'Min shares',
      labelAppreciationRate: 'Appreciation rate',
      labelOccupancyRate: 'Occupancy rate',
      labelManagementFee: 'Management fee',
      labelOwnership: 'Ownership',
      labelDistribution: 'Distribution',
      labelExitModel: 'Exit model',
      labelStatus: 'Status',
      labelReviewedBy: 'Reviewed by',
      labelReviewedAt: 'Reviewed at',
      labelPublishedAt: 'Published at',
      labelVerificationRecord: 'Verification record',
      labelBlockchainStatus: 'Blockchain status',
      labelBlockchainHash: 'Blockchain hash',
      labelBlockchainTx: 'Blockchain tx',
      labelAnchoredAt: 'Anchored at',
      labelCreated: 'Created',
      labelUpdated: 'Updated',
      metricIRR: 'IRR',
      metricPerShare: 'Per Share',
      metricRisk: 'Risk',
      metricHold: 'Hold',
      reviewNotesBanner: 'Review Notes',
      rejectionReasonBanner: 'Rejection Reason',
      notesRejectLabel: 'Rejection reason *',
      notesRejectPlaceholder: 'Enter the reason for rejection…',
      confirmActionPrompt: 'Confirm this action?',
      actionApprove: 'Approve',
      actionPublish: 'Publish',
      actionReject: 'Reject',
      actionUnpublish: 'Unpublish',
      cancelButton: 'Cancel',
      confirmButton: 'Confirm',
      backToInvestments: 'Back to Investments',
      alertDone: 'Done',
      alertActionCompleted: 'Action completed.',
      alertActionFailed: 'Action failed',
      alertActionError: 'Unable to complete the action.',
      alertNotesRequiredTitle: 'Notes required',
      alertNotesRequiredMsg: 'Please enter a rejection reason before submitting.',
      notAssigned: 'Not assigned',
      pendingText: 'Pending',
      loadingText: 'Loading opportunity profile…',
      errorUnavailable: 'Opportunity unavailable',
      errorTryAgain: 'Try again shortly.',
      errorLoad: 'Failed to load opportunity.',
    },
    // User Detail
    userDetail: {
      sectionAccount: 'Account',
      sectionAccountActivity: 'Account & Activity',
      sectionProviderIdentity: 'Provider Identity',
      sectionRegistration: 'Registration & Documents',
      sectionActions: 'Provider Actions',
      labelUsername: 'Username',
      labelRole: 'Role',
      labelEmail: 'Email',
      labelPhone: 'Phone',
      labelJoined: 'Joined',
      labelRegistrationNo: 'Registration No.',
      labelLicenseNo: 'License No.',
      labelCategory: 'Category',
      labelProviderType: 'Provider Type',
      labelProviderStatus: 'Provider Status',
      labelUserId: 'User ID',
      labelAccountType: 'Account type',
      labelProviderVerificationStatus: 'Provider status',
      labelBusinessName: 'Business name',
      labelContactPerson: 'Contact person',
      labelDocuments: 'Documents',
      documentsCount: ' file(s)',
      documentsNone: 'None submitted',
      labelSubmitted: 'Submitted',
      labelReviewed: 'Reviewed',
      statProps: 'Props',
      statInvest: 'Invest',
      statThreads: 'Threads',
      statNotifs: 'Notifs',
      noProfileBadge: 'No Profile',
      noProviderProfile: 'This user has not set up a provider profile yet. Provider actions are not available.',
      joinedPrefix: 'Joined ',
      adminNotesBanner: 'Admin Notes',
      rejectionReasonBanner: 'Rejection Reason',
      notesRejectLabel: 'Rejection reason *',
      notesAdminLabel: 'Admin notes',
      notesRejectPlaceholder: 'Enter the reason for rejection…',
      notesAdminPlaceholder: 'Enter notes for this account…',
      confirmActionPrompt: 'Confirm this action?',
      actionMarkUnderReview: 'Mark Under Review',
      actionVerify: 'Verify',
      actionReject: 'Reject',
      actionSuspend: 'Suspend',
      actionUpdateNotes: 'Update Notes',
      actionSaveNotes: 'Save Notes',
      cancelButton: 'Cancel',
      confirmButton: 'Confirm',
      backToUsers: 'Back to Users',
      alertDone: 'Done',
      alertActionCompleted: 'Action completed.',
      alertActionFailed: 'Action failed',
      alertActionError: 'Unable to complete the action.',
      alertNotesRequiredTitle: 'Notes required',
      alertNotesRequiredMsg: 'Please enter a rejection reason before submitting.',
      actionVerifyProvider: 'Verify Provider',
      actionRejectProvider: 'Reject Provider',
      actionSuspendProvider: 'Suspend Provider',
      loadingText: 'Loading user profile…',
      errorUnavailable: 'User unavailable',
      errorTryAgain: 'Try again shortly.',
      errorLoad: 'Failed to load user.',
    },
    // Label maps — shared across screens
    reportReasons: {
      spam: 'Spam',
      fraud: 'Fraud / Scam',
      misleading_info: 'Misleading Information',
      inappropriate: 'Inappropriate Content',
      duplicate: 'Duplicate Listing',
      other: 'Other',
    },
    reportStatuses: {
      open: 'Open',
      under_review: 'Under Review',
      resolved: 'Resolved',
      dismissed: 'Dismissed',
    },
    flagRules: {
      suspicious_pricing: 'Suspicious Pricing',
      missing_key_data: 'Missing Key Data',
      unrealistic_returns: 'Unrealistic Returns',
      unrealistic_cash_yield: 'Unrealistic Cash Yield',
      duplicate_signal: 'Potential Duplicate',
    },
    audiences: {
      all_citizens: 'All Citizens',
      all_providers: 'All Providers',
      one_user: 'Single User',
    },
    announcementStatuses: {
      active: 'Active',
      archived: 'Archived',
    },
    verificationStatuses: {
      pending_verification: 'Pending Verification',
      needs_changes: 'Needs Changes',
      verified: 'Verified',
      rejected: 'Rejected',
      frozen: 'Frozen',
      sold: 'Sold',
      draft: 'Draft',
    },
    investmentStatuses: {
      draft: 'Draft',
      submitted: 'Submitted',
      under_review: 'Under Review',
      approved: 'Approved',
      published: 'Published',
      rejected: 'Rejected',
    },
    providerStatuses: {
      unverified: 'Unverified',
      under_review: 'Under Review',
      verified: 'Verified',
      rejected: 'Rejected',
      suspended: 'Suspended',
    },
    accountTypes: {
      individual: 'Individual',
      owner: 'Owner',
      agency: 'Agency',
      developer: 'Developer',
      partner: 'Partner',
    },
    severities: {
      low: 'LOW',
      medium: 'MEDIUM',
      high: 'HIGH',
    },
  },
} as const;

export type StringsType = typeof Strings;
